### ISSUE TITLE
[버그] 라우팅 버그

### ISSUE THREAD

**Issue by GiPyoo** [sproutt/eussya-eussya-view#35]
바로 /signup 하면 에러가 생김 웹서버 수정 필요함.

**Comment by Bellroute** [comment]
/signup 이 아니라 /members로 post요청인 것 같습니다.

**Comment by GiPyoo** [comment]
@Bellroute  아 이건 제 라우팅 버그입니다! 웹서에서 제 페이지 이름 경로를 안 정해놔서 그런 것 같습니다! 해결하겠습니다. 감사합니다.
