### ISSUE TITLE
[Feature] 서버에서 제공해주는 동기부여 메세지 ui 전달

### ISSUE THREAD

**Issue by GiPyoo** [sproutt/eussya-eussya-view#56]
**이 기능이 필요한 이유**
항상 다른 문구가 화면에 보이게 해서 사용자로 하여금 매일매일 색다름을 제공해 준다.

**기능 설명**
Request 를 이용하여 서버측에 메시지를 요청하고 메세지가 온전히 오게 된다면 온 메세지를 화면에 띄우고 오지 않는다면 클라이언트에서 제공하는 메세지를 띄운다.

**기능 구현시 고려항 사항**
클린 아키텍쳐를 이번에 재 설계하여 보여준다.

**Comment by acupofmilktea** [comment]
좋은 아이디어 같습니다!
그러면 서버측에서 제공하는 메세지와 클라이언트측에서 제공하는 메세지는 각각 다른 것으로 할 건가요?

**Comment by GiPyoo** [comment]
넵 api 상 문제가 있다면 기존에 정해진 메세지로 다른 것을 띄우려고 합니다.
예시 "게으른 서버로 인해 클라이언트가 고통 받는다" 이런식 :)

**Comment by acupofmilktea** [comment]
> 넵 api 상 문제가 있다면 기존에 정해진 메세지로 다른 것을 띄우려고 합니다.
> 
> 예시 "게으른 서버로 인해 클라이언트가 고통 받는다" 이런식 :)
> 
> 장난스러운 멘트 생각해서

ㅋㅋㅋㅋㅋ 좋은 것 같아요
오류 메세지 직관적으로 띄워주는 것보다 그게 낫겠군요
