### ISSUE TITLE
[Feature] 서버에서 받아온 시간을 프론트에 렌더링

### ISSUE THREAD

**Issue by GiPyoo** [sproutt/eussya-eussya-view#60]
**이 기능이 필요한 이유**
실제 새벽을 달리는 개발자(얼또)는 서버시간을 기준으로 하고 있어야 원활히 모든 유저가 특정 시간에 이용할 수 있기 때문이다.

**기능 설명**
서버에서 시간을 가져와 파싱한 후 서버 시간대를 클라에서 설정 및 시간을 가져와 렌더링 한다. 

**기능 구현시 고려항 사항**
이 시간은 클라에서 사용되는 대부분의 시간 관련된 기능의 기준이 된다.

**Additional context**

**Comment by acupofmilktea** [comment]
서버에 요청은 얼마의 주기로 보내게 되나요?

**Comment by hyukjin-lee** [comment]
@acupofmilktea 주기는 없고 해당 페이지에 접근할 때 마다 요청 보내지 않을까 싶네요
