### ISSUE TITLE
[Fix] 회원가입 화면 - 인증번호 받고 가입 안 했을 경우, 다시 가입 시도하면 이미 가입된 계정이라고 뜸

### ISSUE THREAD

**Issue by hyukjin-lee** [sproutt/eussya-eussya-view#94]
회원가입 화면 - 인증번호 받고 가입 안 했을 경우, 다시 가입 시도하면 이미 가입된 계정이라고 뜸

**Comment by Bellroute** [comment]
이메일로 계정 생성하는 웹 서비스 중 아마존으로 해당 이슈 시도해보니까 인증하지 않고 다시 가입 시도하게되면 인증번호를 한 번 더 전송하도록 하네요! 가입할 이메일이 db에 존재하는데 이메일 인증이 되지 않은 경우 인증 메일을 재전송하고 인증을 유도하도록 수정하겠습니다

**Comment by hyukjin-lee** [comment]
가입 절차가 완료되지 않았음에도 불구하고 저희 DB 에 정보를 저장하는 것이 옳은 것인지도 고민해봐야할 것 같아요.
인증을 하지 않아도 일단 가입한걸로 볼 것 인가, 아니면 가입하지 않은 걸로 볼 것 인가. 이 차이점으로 사용자 경험 flow 가 좀 달라질 수 있겠습니다.

**Comment by Bellroute** [comment]
어쨌든 입력한 이메일과 전송한 인증코드를 서버가 기억하고 있어야할 것 같은데 그러면 세션에 저장해두고 일정 시간 내에 인증을 하지 않으면 세션 날려버리는 방식으로 구현하는 것은 어떤가요? 

아니면, 라이엇게임즈 같은 경우는 휴대폰인증 -> 메일인증 -> 회원정보 입력 순으로 메일 인증을 성공해야만 다음 회원 정보를 입력 받게 하고 과정 중간에 브라우저 벗어나면 다시 처음부터 인증하도록 하던데 이런 ux를 따르는 건 어떨까요?

**Comment by hyukjin-lee** [comment]
세션에 저장하는 방식은 어플리케이션 서버 한대가 장애나서 죽었다가 살아날 경우 해당 서버의 세션에 보관하고 있던 기록이 날라가는 문제가 발생할 수도 있겠네요 

메일인증을 같은 회원가입 창에서 받도록 하는게 어떨까요? (일반적인 회원가입 ux 의 휴대폰인증처럼)
